# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a435a47a1311d6e5a2d8495b870aa877f6070c9a34c4aa3b42242705cdd3c3f142e8338886331308022d1df5858a2108f7a3030b5b762db2325437f335979f4

test:
  secret_key_base: 65ffae644bd7147dfe8be0b1156a38925c1349d624d570202b8bac962f19ad786f8528cf401604d3ac3483d2ad04195f3a8af7f699d9cd2b4fa1f15f28c5fb84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



development:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: 4fdc6a0597a976aa4b836ab95e0605c760f2ad256cbcdb431dc15414de599e601a0e8ad7d5a60f58522fc14cb25803276b8d50980e5ffe87528bed79205307d5

test:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET']%>
  secret_key_base: 3b2802cdac37d8fa8bb84c30ccc78f14487a14707014b4e1b02d888d3031017bb36922e384fc06f9bbfdaac618793a3d0d267d0e28858948e4849148285577a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET']%>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
